name: th_llm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - matplotlib-inline
  - numpy=2.2.5
  - pandas=2.2.3
  - regex=2024.5.15
  - requests=2.32.3
  - filelock=3.18.0
  - pydantic=2.8.2
  - pip
  - notebook

  - pip:
    - diskcache
    - accelerate==1.6.0
    - huggingface-hub==0.30.2
    - openai==1.35.10
    - pydantic_core==2.20.1
    - safetensors==0.4.3
    - tokenizers==0.21.0
    - torch==2.5.1
    - torchaudio==2.5.1
    - torchvision==0.20.1
    - torchviz==0.0.3
    - transformers==4.51.3
    - datasets
    - autoawq
    - inflect
    - langchain
    - langchain_huggingface
    - langchain-community
    - psycopg2-binary
    - geoalchemy2
    - geopandas
    - mem0ai
    - sentence_transformers
    - litellm
    - boto3
    - python-dotenv
    - pypdf
    - qdrant-client
    - ipywidgets
